apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: pleungmsdevops
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: pleungmsdevops
    spec:
      containers:
      - name: pleungtestapp
        image: pleungcon.azurecr.io/pleungms/pleungmsdevops:$BUILD_ID
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pleungmsdevops
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: pleungmsdevops
